import HeadBlock from '../app/components/head/Head'
import Layout from '../app/components/layout/index'
import Main from '../app/components/main/Main'
import fetchProjects from '../app/services/fetchProjects.js'
import { useDispatch } from 'react-redux'
import {setProjects} from '../app/store/slices/allProjects'
import { useEffect } from 'react'

export async function getServerSideProps() {
  try{
    const {projects} = await fetchProjects('realestate')
    if(!projects){
      return { props: { projects :[]} }
    }
    return { props: { projects } }
    
  }catch(error){
    return { props: { projects:[] } }
  }
}

export default function Home({projects}) {
  const dispatch = useDispatch()

  useEffect(() => {
    if(projects){
      dispatch(setProjects(projects))
    }else{
      dispatch(setProjects([]))
    }
  },[])

const pageInfo = {
  title:'Real estate',
  description:
  `
  <div>
    <p>
      One of the best and safest long-term solutions for investing 
      is real-estate. It allows you to have robust returns which 
      are not entirely dependent on the state of the stock market. 
    </p>
    <p>
      Real estate investors make money through rental income, any 
      profits generated by property-dependent business activity, 
      and appreciation. Real estate values tend to increase over
      time, and with a good investment, you can turn a profit 
      when it's time to sell.
    </p>
  </div>
  <div>
    <b>
    No name will provide you various opportunities to invest in real estate:
    </b>
    <ul>
     <li>commercial real estate;</li>
     <li>residential real estate;</li>
     <li>industrial.</li>
    </ul>
    <p>
    Let’s build together
    </p>
  </div>
  `
}

  return (
    < >
      <HeadBlock title={'Real estate'}/>
      <Layout>
        <Main 
        info={pageInfo}
        type={'Real estate'} 
        />
      </Layout>
    </>
  )
}

